
name: Reproduce thesis

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      THESIS_DIR: ./thesis
      THESIS_FILE: thesis
      SLIDES_DIR: ./slides
      SLIDES_FILE: slides
      POSTER_DIR: ./poster
      POSTER_FILE: poster

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up TeX environment
        run: sudo apt-get update && sudo apt-get install texlive texlive-luatex texlive-publishers texlive-science texlive-fonts-extra cm-super dvipng

      - name: Generate matrices
        run: python setup/generate_matrices.py

      - name: Generate plots and tables
        run: python setup/generate_results.py

      - name: Obtain commit hash and time
        run: |
          echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "build_time=$(date +'%Y-%m-%d at %H:%M:%S UTC')" >> $GITHUB_ENV

      - name: Generate thesis
        run: |
          echo "\begin{tikzpicture}" > "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \draw[black, line width=3pt] (0.1, 0.95) to (0.8\textwidth, 0.95) (0.1, -0.95) to (\textwidth, -0.95);" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \fill[white] (0, 1.1) to (1, 1.1) arc (90:-90:1.1) to (0, -1.1);" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \fill[black] (1, 0) circle (1);" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \draw[white, line width=1pt] (0.35, 0.55) arc(140:-80:0.45) to (1.1, -0.65) to (0.95, -0.65) (0.45, 0.45) arc(140:-110:0.31) to (0.58, -0.65) (1.35, -0.65) arc(270:20:0.35) to (1.35, -0.35) (1.35, -0.51) arc(270:50:0.21) (1.43, -0.65) rectangle (1.57, -0.51);" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.1, 0.45) {This document is provably reproducible.};" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.1) {\small \texttt{> hosted at \url{${{ github.server_url }}/${{ github.repository }}}}};" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.5) {\small \texttt{> built on ${{ env.build_time }} from \href{${{ github.server_url }}/${{ github.repository }}/tree/${{ env.sha_short }}}{${{ env.sha_short }}}}};" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          echo "\end{tikzpicture}" >> "${{ env.THESIS_DIR }}/re-pro-badge.tex"
          python setup/generate_thesis.py

      - name: Generate slides
        run: |
          echo "\begin{tikzpicture}" > "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \draw[black, line width=3pt] (0.1, 0.95) to (0.8\textwidth, 0.95) (0.1, -0.95) to (\textwidth, -0.95);" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \fill[white] (0, 1.1) to (1, 1.1) arc (90:-90:1.1) to (0, -1.1);" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \fill[black] (1, 0) circle (1);" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \draw[white, line width=1pt] (0.35, 0.55) arc(140:-80:0.45) to (1.1, -0.65) to (0.95, -0.65) (0.45, 0.45) arc(140:-110:0.31) to (0.58, -0.65) (1.35, -0.65) arc(270:20:0.35) to (1.35, -0.35) (1.35, -0.51) arc(270:50:0.21) (1.43, -0.65) rectangle (1.57, -0.51);" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.1, 0.45) {This document is provably reproducible.};" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.1) {\small \texttt{> hosted at \url{${{ github.server_url }}/${{ github.repository }}}}};" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.5) {\small \texttt{> built on ${{ env.build_time }} from \href{${{ github.server_url }}/${{ github.repository }}/tree/${{ env.sha_short }}}{${{ env.sha_short }}}}};" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          echo "\end{tikzpicture}" >> "${{ env.SLIDES_DIR }}/re-pro-badge.tex"
          python setup/generate_slides.py

      - name: Generate poster
        run: |
          echo "\begin{tikzpicture}" > "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \fill[white] (1, 0) circle (1.05);" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \fill[darkblue] (1, 0) circle (1);" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \draw[white, line width=1pt] (0.35, 0.55) arc(140:-80:0.45) to (1.1, -0.65) to (0.95, -0.65) (0.45, 0.45) arc(140:-110:0.31) to (0.58, -0.65) (1.35, -0.65) arc(270:20:0.35) to (1.35, -0.35) (1.35, -0.51) arc(270:50:0.21) (1.43, -0.65) rectangle (1.57, -0.51);" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.1, 0.65) {\small This document is provably reproducible.};" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.1) {\footnotesize \texttt{> hosted at \url{${{ github.server_url }}/${{ github.repository }}}}};" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "    \node[anchor=west] at (2.3, -0.75) {\footnotesize \texttt{> built on ${{ env.build_time }} from \href{${{ github.server_url }}/${{ github.repository }}/tree/${{ env.sha_short }}}{${{ env.sha_short }}}}};" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          echo "\end{tikzpicture}" >> "${{ env.POSTER_DIR }}/re-pro-badge.tex"
          python setup/generate_poster.py

      - name: Upload thesis as PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: outcomes
          path: |
            ${{ env.THESIS_DIR }}/${{ env.THESIS_FILE }}.pdf
            ${{ env.SLIDES_DIR }}/${{ env.SLIDES_FILE }}.pdf
            ${{ env.POSTER_DIR }}/${{ env.POSTER_FILE }}.pdf

      - name: Upload generated files to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add thesis/plots/*.pgf thesis/tables/*.tex */re-pro-badge.tex
          git commit -m "reproduce thesis"
          git push
